name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and save Docker image
      run: |
        docker build --build-arg SHOULD_COMPILE=true -t episim-validation .
        docker save episim-validation > /tmp/episim-validation.tar
    
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/episim-validation.tar

  python-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: /tmp
    
    - name: Load Docker image
      run: docker load < /tmp/episim-validation.tar
    
    - name: Run Python code quality checks
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          episim-validation \
          bash -c "cd python && uv run ruff check . && uv run ruff format --check ."
      continue-on-error: true
    
    - name: Run Python tests
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -v $(pwd)/models/mitma:/data \
          -w /workspace \
          episim-validation \
          bash -c "cd python && uv run pytest tests/ -v"
    
  julia-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: /tmp
    
    - name: Load Docker image
      run: docker load < /tmp/episim-validation.tar
    
    - name: Run Julia tests
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -v $(pwd)/models/mitma:/data \
          -w /workspace \
          episim-validation \
          julia --project=. test/runtests.jl
