name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t episim-validation .
    
    - name: Run Python code quality checks
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          episim-validation \
          bash -c "cd python && uv run ruff check . && uv run ruff format --check ."
      continue-on-error: true
    
    - name: Run Python tests with coverage
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -v $(pwd)/models/mitma:/data \
          -w /workspace \
          episim-validation \
          bash -c "cd python && uv run pytest tests/ -v --cov=episim_python --cov-report=xml --cov-report=term || uv run pytest tests/ -v"
    
    - name: Run Julia tests
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -v $(pwd)/models/mitma:/data \
          -w /workspace \
          episim-validation \
          julia --project=. test/runtests.jl
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./python/coverage.xml
        flags: python
        name: python-coverage
        fail_ci_if_error: false
